theme = "catppuccin_mocha_custom"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
color-modes = true
mouse = true
rulers = [88]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
